name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Project_Path: AsylumLauncher/AsylumLauncher.csproj # Path to your Avalonia UI project

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Project_Path }}

    # Build the project
    - name: Build the project
      run: dotnet build ${{ env.Project_Path }} --configuration ${{ matrix.configuration }}

    # Publish the project to generate a .exe artifact
    - name: Publish the project
      run: dotnet publish ${{ env.Project_Path }} -c ${{ matrix.configuration }} -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true

    # Upload the .exe artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Exe Artifact
        path: ${{ env.Project_Path }}/bin/${{ matrix.configuration }}/net8.0/win-x64/publish
